-- ========================================
-- EASYFOX DATABASE SCHEMA - COMPLETE
-- ========================================
-- RUN THIS FILE IN SUPABASE SQL EDITOR
-- 
-- ⚠️  IMPORTANT NOTE: CHỈ CHỈNH SỬA FILE NÀY THÔI!
-- - Mọi thay đổi database chỉ được thực hiện trong file này
-- - Nếu cần reset database, sử dụng file reset_database.sql trước
-- - Không tạo migration files riêng lẻ nữa
-- ========================================

-- Enable RLS (Row Level Security)
ALTER TABLE IF EXISTS public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.settings ENABLE ROW LEVEL SECURITY;

-- ========================================
-- USERS TABLE
-- ========================================
-- Extends Supabase auth.users with business information
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    notes TEXT, -- For AI onboarding information (business description)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- CHAT HISTORY TABLE
-- ========================================
-- Stores all chat conversations with AI
CREATE TABLE IF NOT EXISTS public.chat_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    question TEXT, -- User's question (can be null for AI-initiated messages)
    ai_response TEXT, -- AI's response (can be null for user-only messages)
    chat_session_id TEXT NOT NULL, -- Groups messages in same conversation
    toolinvocations JSONB, -- Store tool calls and results
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- CAMPAIGNS TABLE
-- ========================================
-- Marketing campaigns with date ranges
CREATE TABLE IF NOT EXISTS public.campaigns (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    budget DECIMAL(10,2),
    target_audience TEXT,
    goals TEXT, -- Marketing objectives
    content_pillars JSONB, -- Store as JSON array
    notes TEXT, -- AI-collected information and conversation history
    start_date DATE, -- Campaign start date
    end_date DATE, -- Campaign end date
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- SCHEDULE TABLE
-- ========================================
-- 4-tier content structure for social media scheduling
CREATE TABLE IF NOT EXISTS public.schedule (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    campaign_id UUID REFERENCES public.campaigns(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    scheduled_date TIMESTAMPTZ NOT NULL,
    platform TEXT NOT NULL, -- 'facebook', 'instagram', 'tiktok', etc.
    content_pillar TEXT, -- Tier 1: Content Pillars
    content_category TEXT, -- Tier 2: Content Categories  
    content_angle TEXT, -- Tier 3: Content Angles
    content_brief TEXT, -- Tier 4: Content Brief (generated by AI)
    full_content TEXT, -- Final content (approved by user)
    image_url TEXT,
    video_url TEXT,
    status TEXT DEFAULT 'draft', -- 'draft', 'approved', 'posted'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- SETTINGS TABLE
-- ========================================
-- User preferences and configuration
CREATE TABLE IF NOT EXISTS public.settings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, key)
);

-- ========================================
-- INDEXES FOR PERFORMANCE
-- ========================================
CREATE INDEX IF NOT EXISTS idx_chat_history_user_id ON public.chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_created_at ON public.chat_history(created_at);
CREATE INDEX IF NOT EXISTS idx_chat_history_session_id ON public.chat_history(chat_session_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_user_id ON public.campaigns(user_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_dates ON public.campaigns(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_schedule_user_id ON public.schedule(user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_campaign_id ON public.schedule(campaign_id);
CREATE INDEX IF NOT EXISTS idx_schedule_date ON public.schedule(scheduled_date);
CREATE INDEX IF NOT EXISTS idx_settings_user_id ON public.settings(user_id);

-- ========================================
-- ROW LEVEL SECURITY POLICIES
-- ========================================

-- Users can only see their own data
CREATE POLICY "Users can view own profile" ON public.users
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
    FOR UPDATE USING (auth.uid() = id);

-- Chat history policies
CREATE POLICY "Users can view own chat history" ON public.chat_history
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own chat history" ON public.chat_history
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own chat history" ON public.chat_history
    FOR UPDATE USING (auth.uid() = user_id);

-- Campaigns policies
CREATE POLICY "Users can view own campaigns" ON public.campaigns
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own campaigns" ON public.campaigns
    FOR ALL USING (auth.uid() = user_id);

-- Schedule policies
CREATE POLICY "Users can view own schedule" ON public.schedule
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own schedule" ON public.schedule
    FOR ALL USING (auth.uid() = user_id);

-- Settings policies
CREATE POLICY "Users can view own settings" ON public.settings
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own settings" ON public.settings
    FOR ALL USING (auth.uid() = user_id);

-- ========================================
-- FUNCTIONS & TRIGGERS
-- ========================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for updated_at
CREATE TRIGGER handle_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_campaigns_updated_at
    BEFORE UPDATE ON public.campaigns
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_schedule_updated_at
    BEFORE UPDATE ON public.schedule
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_settings_updated_at
    BEFORE UPDATE ON public.settings
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- ========================================
-- COMPLETION MESSAGE
-- ========================================
-- Success message
DO $$
BEGIN
    RAISE NOTICE '✅ EasyFox Database Schema Created Successfully!';
    RAISE NOTICE '📋 Tables: users, chat_history, campaigns, schedule, settings';
    RAISE NOTICE '🔒 RLS Policies: Enabled for all tables';
    RAISE NOTICE '⚡ Indexes: Created for performance optimization';
END $$;
